### ISSUE TITLE
Issue while disabling in 1.17.1

### ISSUE THREAD

**Issue by CroaBeast** [nvx/CleanroomGenerator#27]
This issue shows in the console when the plugin is disabled.
```
[22:14:59 INFO]: [CleanroomGenerator] Disabling CleanroomGenerator v1.1.1
[22:14:59 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[22:14:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552)
[22:14:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:265)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.SafeLocationFinderOtherThread.getChunkForLocation(SafeLocationFinderOtherThread.java:93)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.SafeLocationFinderOtherThread.dropToGround(SafeLocationFinderOtherThread.java:64)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.SafeLocationFinder.moveToStart(SafeLocationFinder.java:161)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.SafeLocationFinder.tryAndMakeSafe(SafeLocationFinder.java:79)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.RandomTeleporter.getRtpLocation(RandomTeleporter.java:424)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.RandomTeleporter.fillQueue(RandomTeleporter.java:480)
[22:14:59 WARN]:        at JakesRTP-v0.14.2.jar//biz.donvi.jakesRTP.LocationCacheFiller.run(LocationCacheFiller.java:37)
[22:14:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:14:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:14:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:14:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:14:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:14:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by nvx** [comment]
The Cleanroom Generator plugin doesn't register any tasks, and the stack trace doesn't mention Cleanroom Generator either, only a plugin called JakesRTP.

At any rate I'm not sure what value there is in disabling a world generator plugin. Unless a world is configured to use the world generator plugin it won't be doing anything (at which point you could safely delete the jar file anyway), but if a world is configured to use it disabling the world generator plugin would likely break hard anyway. You'd need to delete any worlds using the world generator first.

**Comment by nvx** [comment]
Going to close off this old issue as I suspect it's a problem with JakesRTP not CleanroomGenerator.
